export const ESTATE_DRAWING_CHANGE_MODAL = 'ESTATE_DRAWING_CHANGE_MODAL'

export const ESTATE_DRAWING_CLOSE_MODAL = 'ESTATE_DRAWING_CLOSE_MODAL'

export const ESTATE_DRAWING_CHANGE_SELECTED_PROPERTY = 'ESTATE_DRAWING_CHANGE_SELECTED_PROPERTY'
