const SORT_RULE = {
  AVA_PROPERTYCOUNT_DESC: 'AVA_PROPERTYCOUNT_DESC',
  AVA_PROPERTYCOUNT_ASC: 'AVA_PROPERTYPECOUNT_ASC',
  PROPERTYCOUNT_DESC: 'PROPERTYCOUNT_DESC',
  PROPERTYCOUNT_ASC: 'PROPERTYCOUNT_ASC',
  REALSUR_PROPERTYCOUNT_DESC: 'REALSUR_PROPERTYCOUNT_DESC',
  REALSUR_PROPERTYCOUNT_ASC: 'REALSUR_PROPERTYCOUNT_ASC',
  KEY_PROPERTYCOUNT_DESC: 'KEY_PROPERTYCOUNT_DESC',
  KEY_PROPERTYCOUNT_ASC: 'KEY_PROPERTYCOUNT_ASC',
  TRUSTREC_PROPERTYCOUNT_DESC: 'TRUSTREC_PROPERTYCOUNT_DESC',
  TRUSTREC_PROPERTYCOUNT_ASC: 'TRUSTREC_PROPERTYCOUNT_ASC',
  BMRECOM_PROPERTYCOUNT_DESC: 'BMRECOM_PROPERTYCOUNT_DESC',
  BMRECOM_PROPERTYCOUNT_ASC: 'BMRECOM_PROPERTYCOUNT_ASC',
  DMRECOM_PROPERTYCOUNT_DESC: 'DMRECOM_PROPERTYCOUNT_DESC',
  DMRECOM_PROPERTYCOUNT_ASC: 'DMRECOM_PROPERTYCOUNT_ASC'
}

export default SORT_RULE
