const SORT_RULE = {
  AVA_PROPERTYCOUNT_DESC: 'AVA_PROPERTYCOUNT_DESC',
  AVA_PROPERTYCOUNT_ASC: 'AVA_PROPERTYCOUNT_ASC',
  PROPERTYCOUNT_DESC: 'PROPERTYCOUNT_DESC',
  PROPERTYCOUNT_ASC: 'PROPERTYCOUNT_ASC',
  REALSUR_PROPERTYCOUNT_DESC: 'REALSUR_PROPERTYCOUNT_DESC',
  REALSUR_PROPERTYCOUNT_ASC: 'REALSUR_PROPERTYCOUNT_ASC',
  KEY_PROPERTYCOUNT_DESC: 'KEY_PROPERTYCOUNT_DESC',
  KEY_PROPERTYCOUNT_ASC: 'KEY_PROPERTYCOUNT_ASC',
  TRUSTREC_PROPERTYCOUNT_DESC: 'TRUSTREC_PROPERTYCOUNT_DESC',
  TRUSTREC_PROPERTYCOUNT_ASC: 'TRUSTREC_PROPERTYCOUNT_ASC',
  RECOM_PROPERTYCOUNT_DESC: 'RECOM_PROPERTYCOUNT_DESC',
  RECOM_PROPERTYCOUNT_ASC: 'RECOM_PROPERTYCOUNT_ASC',
  PHONE_PROPERTYCOUNT_DESC: 'PHONE_PROPERTYCOUNT_DESC',
  PHONE_PROPERTYCOUNT_ASC: 'PHONE_PROPERTYCOUNT_ASC',
  ADM_PROPERTYCOUNT_DESC: 'ADM_PROPERTYCOUNT_DESC',
  ADM_PROPERTYCOUNT_ASC: 'ADM_PROPERTYCOUNT_ASC'
}

export default SORT_RULE
