export const REQUEST_DATA = 'REQUEST_DATA'

export const FETCH_DATA = 'FETCH_DATA'

export const RECEIVE_DATA = 'RECEIVE_DATA'

export const REQUEST_EXPORT_DATA_CODE = 'REQUEST_EXPORT_DATA_CODE'

export const FETCH_EXPORT_DATA_CODE = 'FETCH_EXPORT_DATA_CODE'

export const RECEIVE_EXPORT_DATA_CODE = 'RECEIVE_EXPORT_DATA_CODE'

export const DOWNLOAD_EXPORTD_DATA = 'DOWNLOAD_EXPORT_DATA'
