export const ADD_DISTRICT_ID = 'ADD_DISTRICT_ID'

export const REMOVE_DISTRICT_ID = 'REMOVE_DISTRICT_ID'

export const ADD_REGION_ID = 'ADD_REGION_ID'

export const REMOVE_REGION_ID = 'REMOVE_REGION_ID'

export const REMOVE_REGION_IDS = 'REMOVE_REGION_IDS'

export const ADD_REGION_IDS = 'ADD_REGION_IDS'

export const CLEAR_REGION_IDS = 'CLEAR_REGION_IDS'
