export const ADD_DISTRICT_ID = 'ADD_DISTRICT_ID'

export const REMOVE_DISTRICT_ID = 'REMOVE_DISTRICT_ID'

export const ADD_REGION_ID = 'ADD_REGION_ID'

export const REMOVE_REGION_ID = 'REMOVE_REGION_ID'
