export const CHANGE_ORDER_RULE = 'CHANGE_ORDER_RULE'

export const FETCH_NEXT_PAGE = 'FETCH_NEXT_PAGE'

export const FETCH_SELECTED_PAGE = 'FETCH_SELECTED_PAGE'

export const FETCH_PRE_PAGE = 'FETCH_PRE_PAGE'

export const FETCH_FIRST_PAGE = 'FETCH_FIRST_PAGE'

export const FETCH_LAST_PAGE = 'FETCH_LAST_PAGE'
